P:
  START:
    - "8:40"
    - "10:10"
    - "12:15"
    - "13:45"
    - "15:15"
    - "16:45"
  END:
    - "9:55"
    - "11:25"
    - "13:30"
    - "15:00"
    - "16:30"
    - "18:00"
TERM:
  # 学年暦 ref
  # http://www.tsukunavi.com/life/shinseikatsu2015/daigaku/schedule.html
  BEGIN:
    春:
      A: 2015/04/07
      B: 2015/05/23
      C: 2015/07/04
    夏: 2015/08/09
    秋:
      A: 2015/10/01
      B: 2015/11/08
      C: 2015/12/24
  # 13:00 となっているのは、GMTで指定するため (JSTなら、22:00)
  END:
    春:
      A: 2015/05/22 13:00
      B: 2015/07/01 13:00
      C: 2015/08/06 13:00
    夏: 2015/09/30 13:00
    秋:
      A: 2015/11/07 13:00
      B: 2015/12/26 13:00
      C: 2016/02/12 13:00
database:
  filename: "kamoku.db"
  table_name: "kamoku"
  column_names:
    - "code"
    - "name"
    - "method"
    - "unit"
    - "grade"
    - "term"
    - "period"
    - "location"
    - "teacher"
    - "abstruct"
    - "note"
    - "research_students"
    - "reason"
    - "english_name"
    - "time"
